version: '3'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 1Secure*Password1
      ACCEPT_EULA: Y
      MSSQL_PID: Developer

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  oracle:
    image: gvenzl/oracle-xe:21
    ports:
      - "1521:1521"
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: ORACLE
      APP_USER_PASSWORD: ORACLE

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
