version: '3'

services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./public/:/ci4proj/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  phpfpm:
    build:
      context: ./docker/phpfpm/
      dockerfile: ./Dockerfile
    volumes:
      - ./:/ci4proj

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 1Secure*Password1
      ACCEPT_EULA: Y
      MSSQL_PID: Developer

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
